//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webNew3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.CustomerOrders = new HashSet<CustomerOrder>();
        }
    
        public int BookId { get; set; }
        public int AuthorId { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public decimal Price { get; set; }
        public string BookTitle { get; set; }
        public string BookCover { get; set; }
        public bool InStock { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual ICollection<CustomerOrder> CustomerOrders { get; set; }
    }
}
