//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webNew3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.CustomerAdresses = new HashSet<CustomerAdress>();
            this.CustomerContactDatas = new HashSet<CustomerContactData>();
            this.CustomerOrders = new HashSet<CustomerOrder>();
        }
    
        public int CustomerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual ICollection<CustomerAdress> CustomerAdresses { get; set; }
        public virtual ICollection<CustomerContactData> CustomerContactDatas { get; set; }
        public virtual ICollection<CustomerOrder> CustomerOrders { get; set; }
    }
}
